### ISSUE TITLE
Simplify `ni get` syntax

### ISSUE THREAD

**Issue by ahpook** [puppetlabs/relay#53]
## Use Case
The `ni get` syntax requires retrieving specification data using [json path template](https://kubernetes.io/docs/reference/kubectl/jsonpath/); it should provide a less-punctuated option, particularly for basic use cases that refer to root-level specification data or other simplistic specification paths. This would provide a more fluid and readable syntax and an improved user experience, while retaining the full functionality of the current system and support for a variety of languages used to retrieve specification data.

## Describe the Solution You Would Like
For compatibility we could preserve the existing syntax but add support for a positional command-line parameter after `ni get` that is interpreted as a specification path directly (without the need for the `-p` notation) and uses a simpler syntax by default.

Referencing the [pagerduty-to-jira workflow](https://github.com/puppetlabs/relay-workflows/blob/master/pagerduty-to-jira/pagerduty-to-jira.yaml):

`ni get connection.url`
would be equivalent to the current
`ni get -p {.connection.url}`

Referencing the [ec2-reaper workflow](https://github.com/puppetlabs/relay-workflows/blob/master/ec2-reaper/ec2-reaper.yaml):

`ni get terminationDateTag`
would be equivalent to the current
`ni get -p {.terminationDateTag}`

This is not related to parameters (even tangentially).

## Describe Alternatives You've Considered
We could change the current behaviour but it would break everything.

**Comment by rick-a-lane-ii** [comment]
- Upgrade `ni get` to support all of our current language paths for the specification
- Change the default language path to match the current default language path (reference [Lodash get](https://lodash.com/docs/4.17.15#get) or [gval](https://github.com/PaesslerAG/gval) for more details on this path language)
- Add the ability to use a different language path (i.e. the original json path implementation). Include this as an optional parameter.
- Drop the use of `-p` to specify the path and add this directly to the command as mentioned above.

This will provide functionality similar to `ni get x.y` instead of `ni get -p {.x.y}` (by default). With an optional syntax that would allow something similar to `ni get {.x.y} --lang jsonpath --output yaml` or `ni get {.x.y} -l jsonpath -o yaml` accordingly.

The use of "param" and parameter in this issue should be removed, as it could cause confusion with our parameters.
